### ISSUE TITLE
1.1 Release Checklist

### ISSUE THREAD

**Issue by markhibberd** [markhibberd/pirate#15]
- [x] Usage.
- [x] Error messages.
- [x] Zero or more argument support.
- [x] One or more argument support.
- [ ] Left associative "many" arguments, i.e. `cp source... dest`.
- [x] Right associtative "many" arguments, i.e. `xargs utility args...`.
- [ ] Fix type inference on flag/switch/argument declarations when using `|*|`.
- [ ] Fix type inference for around handling exposed subtypes of case class ADT encoding.
- [ ] Support explicit `Read` for non canonical parsing.
- [x] Generally better field builder api, description etc...
- [x] Basic parsing preferences.
- [x] Support for `x=y` style arguments.
- [ ] Moar tests.
